name: Lynx Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile Engine
      # Engine is in the root
      run: gcc main.c scanner.c parser.c memory.c -o lynx.exe

    - name: Compile Installer
      # Installer is now in the /installer subfolder
      run: gcc installer/install.c -lurlmon -o LynxInstaller.exe

    - name: Upload Lynx Engine
      uses: actions/upload-artifact@v4
      with:
        name: lynx-exe
        path: lynx.exe

    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: LynxInstaller-exe
        path: LynxInstaller.exe
