name: Lynx  Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile Lynx
      run: gcc main.c scanner.c parser.c memory.c -o lynx.exe

    - name: Run Integration Test
      run: |
        $testScript = @"
        Stalk_Pack "math.lnx"
        Set score = 10 + 5
        Set multiplier = 2
        Set total = score * multiplier
        Roar total
        Stash "savegame.lnx"
        Hunt
        Help
        "@
        $testScript | ./lynx.exe

    - name: Upload Lynx Binary
      uses: actions/upload-artifact@v4
      with:
        name: lynx-v1.3-windows
        path: lynx.exe
