name: Lynx Engine Windows Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: gcc main.c scanner.c parser.c memory.c -o lynx.exe
    - name: Test Module System
      run: |
        # Create a pack
        "Set pi = 3.14" | Out-File -FilePath math_pack.lnx -Encoding ascii
        # Run main script that imports it
        "Stalk_Pack ""math_pack.lnx""
        Roar pi" | ./lynx.exe
    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: lynx-engine
        path: lynx.exe
