name: Build Lynx Engine

on: [push]

jobs:
  build-engine:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile Engine
      run: gcc main.c scanner.c parser.c memory.c libloader.c -o lynx.exe -lurlmon

    - name: Upload Engine Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lynx-engine
        path: lynx.exe
