name: Build Lynx Installer

on: [push]

jobs:
  build-installer:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile Installer
      run: gcc installer/install.c -lurlmon -o LynxInstaller.exe

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lynx-installer
        path: LynxInstaller.exe
